"""WP-G: generate runs/AGGREGATE_V4.md (all tables and numbers) from the V4 run outputs.

Usage: python aggregate_v4.py
Conclusions live in a SEPARATE file (CONCLUSIONS_V4.md) that this script never touches.
Independent unit = (model, seed, concept, region) per task doc section 2.5.
"""
import json, os, glob, sys
from pathlib import Path
import numpy as np
import pandas as pd

L0 = 0.9
EQ = 0.05
METHODS = ["euc_ctx", "cau_ctx", "dua_ctx", "euc_unemb", "cau_unemb", "dua_unemb", "euc_dmd", "cau_dmd", "dua_dmd"]
CONFIRM = [("euc_dmd", "dua_dmd", "C1"), ("cau_unemb", "dua_unemb", "C2")]


def runs_in(pattern):
    return sorted(d for d in glob.glob(pattern) if os.path.exists(f"{d}/summary.csv"))


def meta_of(d):
    cfg = json.load(open(f"{d}/config.json")); chk = json.load(open(f"{d}/checks.json"))
    dd = cfg["args"]["data_dir"] or "synthetic"
    model = "gemma-1b" if "gemma1b" in dd else "gemma-4b" if "gemma4b" in dd else "gpt2" if "gpt2" in dd else dd
    concept = "ing" if "_ing_" in dd or dd.endswith("_ing_s0") or "ing_s" in dd else "third"
    region = "C" if "_c4_" in dd else "A"
    return dict(dir=d, model=model, seed=cfg["args"]["seed"], alpha=cfg["args"].get("alpha_abs"),
                concept=concept, region=region, chk=chk, cfg=cfg)


def fmt(t, nd=3):
    if t is None or not np.isfinite(t[0]): return "n/a"
    return f"{t[0]:.{nd}f} [{t[1]:.{nd}f},{t[2]:.{nd}f}]"


def main():
    R = [meta_of(d) for pat in ["runs/gemma1b_v4/s*", "runs/gpt2_v4/s*", "runs/gemma4b_v4/s*",
                                "runs/gemma1b_v4/c4_s*", "runs/gemma1b_v4/ing_s*", "runs/gpt2_v4/ing_s*"]
         for d in runs_in(pat)]
    L = []
    L.append("# V4 aggregate (auto-generated by aggregate_v4.py; conclusions are in CONCLUSIONS_V4.md)")
    L.append("")
    L.append(f"Primary level {L0}; equivalence margin +-{EQ} KL. Independent unit = (model, seed, concept, region); "
             "fixed methods are alpha-independent and counted once per unit; adaptive alphas are within-unit sensitivity. "
             "CIs: cluster bootstrap (subjects for template runs, doc-ids for C4 runs). No multiple-comparison correction (uncorrected).")
    L.append("")

    # ---- 1. data & checks
    L.append("## 1. Data and guardrail checks")
    L.append("")
    L.append("| run | model | seed | concept | region | alpha | logits_rel_err | probe AUC | base kept | target kept | n_steered | ci_type | cf0_mean |")
    L.append("|---|---|---|---|---|---|---|---|---|---|---|---|---|")
    for r in sorted(R, key=lambda x: (x["model"], x["concept"], x["region"], x["seed"], str(x["alpha"]))):
        c = r["chk"]
        L.append(f"| `{r['dir']}` | {r['model']} | {r['seed']} | {r['concept']} | {r['region']} | {r['alpha']} | "
                 f"{c.get('logits_rel_err'):.2e} | {c.get('probe_heldout_auc'):.3f} | {c.get('n_base_kept')}/{c.get('n_base_raw')} | "
                 f"{c.get('n_target_kept')}/{c.get('n_target_raw')} | {c.get('n_steered')} | {c.get('ci_type')} | {c.get('cf0_mean_test'):.3f} |")
    L.append("")

    # ---- 2. regression vs V3
    L.append("## 2. WP-A1 regression vs V3 (hard gate: <= 1e-6 on shared summary columns)")
    L.append("")
    shared = ["model", "method", "level", "n_start", "n_reached", "reach_rate", "cf_mean", "cf_lo", "cf_hi",
              "kl_mean", "kl_lo", "kl_hi", "steps_mean", "kl99_mean", "kl99_lo", "kl99_hi", "rd_mean", "rd_lo", "rd_hi"]
    num = [c for c in shared if c not in ("model", "method", "level")]
    worst = 0.0; nruns = 0; rows = []
    for r in R:
        if r["concept"] != "third" or r["region"] != "A": continue
        v3 = {"gemma-1b": "runs/gemma1b_v3", "gpt2": "runs/gpt2_v3", "gemma-4b": "runs/gemma4b_v3"}[r["model"]]
        name = os.path.basename(r["dir"])
        f3 = f"{v3}/{name}/summary.csv"
        if not os.path.exists(f3): continue
        a = pd.read_csv(f3)[shared]; b = pd.read_csv(f"{r['dir']}/summary.csv")[shared]
        m = a.merge(b, on=["model", "method", "level"], suffixes=("_3", "_4"))
        A = m[[f"{c}_3" for c in num]].values; B = m[[f"{c}_4" for c in num]].values
        nan_mm = int((np.isnan(A) != np.isnan(B)).sum())
        ok = ~np.isnan(A) & ~np.isnan(B)
        mx = float(np.abs(A[ok] - B[ok]).max()) if ok.any() else 0.0
        worst = max(worst, mx); nruns += 1
        rows.append(f"| `{r['dir']}` | {nan_mm} | {mx:.1e} |")
    L.append("| run | NaN-pattern mismatches | max abs diff (non-NaN cells) |")
    L.append("|---|---|---|")
    L.extend(rows)
    L.append(f"\nRuns compared: {nruns}; overall max diff: {worst:.1e} "
             f"({'PASS (bit-identical)' if worst <= 1e-6 and worst == 0.0 else 'PASS' if worst <= 1e-6 else 'FAIL'}).")
    L.append("")

    # ---- 3. grid main table per region/concept at alpha 5e-3
    L.append(f"## 3. 3x3 grid at level {L0}, alpha 5e-3 (per region/concept; means [cluster-bootstrap CI])")
    L.append("")
    for region, concept in [("A", "third"), ("C", "third"), ("A", "ing")]:
        rs = [r for r in R if r["region"] == region and r["concept"] == concept and str(r["alpha"]) == "0.005"]
        if not rs: continue
        L.append(f"### region {region}, concept {concept} ({len(rs)} runs)")
        L.append("")
        L.append("| run | method | reach | kl | kl_bin | kl_pair | kl_neu | cf_dev | rd | kl99 | steps |")
        L.append("|---|---|---|---|---|---|---|---|---|---|---|")
        for r in sorted(rs, key=lambda x: x["seed"]):
            s = pd.read_csv(f"{r['dir']}/summary.csv"); s9 = s[s.level == L0].set_index("method")
            t = pd.read_csv(f"{r['dir']}/timing.csv").groupby("method").seconds.mean()
            for m in METHODS:
                if m not in s9.index: continue
                x = s9.loc[m]
                L.append(f"| `{os.path.basename(r['dir'])}` | {m} | {x.reach_rate:.2f} | {fmt((x.kl_mean, x.kl_lo, x.kl_hi))} | "
                         f"{fmt((x.klbin_mean, x.klbin_lo, x.klbin_hi))} | {fmt((x.klpair_mean, x.klpair_lo, x.klpair_hi))} | "
                         f"{fmt((x.klneu_mean, x.klneu_lo, x.klneu_hi))} | {fmt((x.cfdev_mean, x.cfdev_lo, x.cfdev_hi))} | "
                         f"{fmt((x.rd_mean, x.rd_lo, x.rd_hi))} | {fmt((x.kl99_mean, x.kl99_lo, x.kl99_hi))} | {x.steps_mean:.0f} |")
        L.append("")

    # ---- 4. confirmatory C1/C2 + D1-D3 with independent units
    L.append(f"## 4. Pre-specified comparisons at level {L0}")
    L.append("")
    L.append("### C1 / C2 (confirmatory; kl)")
    L.append("")
    L.append("| region | concept | seed(s) | comparison | n_paired | diff [CI] | rel | frac ctx b better | units with same sign |")
    L.append("|---|---|---|---|---|---|---|---|---|")
    for region, concept in [("C", "third"), ("A", "third"), ("A", "ing")]:
        rs = [r for r in R if r["region"] == region and r["concept"] == concept]
        for a, b, name in CONFIRM:
            pts = []
            for r in sorted(rs, key=lambda x: (x["seed"], str(x["alpha"]))):
                pl = pd.read_csv(f"{r['dir']}/paired_long.csv")
                q = pl[(pl.a == a) & (pl.b == b) & (pl.metric == "kl") & (np.abs(pl.level - L0) < 1e-9)]
                if not len(q): continue
                row = q.iloc[0]
                base = pd.read_csv(f"{r['dir']}/summary.csv")
                base = base[(base.level == L0) & (base.method == a)]
                rel = row.diff_mean / base.kl_mean.iloc[0] if len(base) and np.isfinite(base.kl_mean.iloc[0]) else float("nan")
                pts.append((r["seed"], str(r["alpha"]), row, rel))
            # one row per seed: prefer 5e-3, others as alpha sensitivity
            for sd in sorted({p[0] for p in pts}):
                main = [p for p in pts if p[0] == sd and p[1] == "0.005"] or [p for p in pts if p[0] == sd]
                others = [p for p in pts if p[0] == sd and p[1] != "0.005"]
                row, rel = main[0][2], main[0][3]
                same = sum(1 for p in pts if np.sign(p[2].diff_mean) == np.sign(row.diff_mean))
                L.append(f"| {region} | {concept} | {sd} | {name}: {a} vs {b} | {row.n_paired} | "
                         f"{fmt((row.diff_mean, row.diff_lo, row.diff_hi))} | {rel:+.0%} | {row.frac_ctx_b_better} | "
                         f"{same}/{len(pts)} rows (incl. alpha sensitivity)" + (f"; other alphas: " + ", ".join(f"{p[1]}:{p[2].diff_mean:+.3f}" for p in others) if others else "") + " |")
    L.append("")
    L.append("### D1 (descriptive): KL decomposition of C1/C2 at alpha 5e-3")
    L.append("")
    L.append("| region | seed | pair | kl_bin | kl_pair | kl_neu | cf_dev |")
    L.append("|---|---|---|---|---|---|---|")
    for region in ["A", "C"]:
        rs = [r for r in R if r["region"] == region and r["concept"] == "third" and str(r["alpha"]) == "0.005"]
        for r in sorted(rs, key=lambda x: x["seed"]):
            for a, b, name in CONFIRM:
                pl = pd.read_csv(f"{r['dir']}/paired_long.csv")
                cells = []
                for met in ["kl_bin", "kl_pair", "kl_neu", "cf_dev"]:
                    q = pl[(pl.a == a) & (pl.b == b) & (pl.metric == met) & (np.abs(pl.level - L0) < 1e-9)]
                    cells.append(fmt((q.diff_mean.iloc[0], q.diff_lo.iloc[0], q.diff_hi.iloc[0])) if len(q) else "n/a")
                L.append(f"| {region} | {r['seed']} | {name} | " + " | ".join(cells) + " |")
    L.append("")
    L.append("### D3 (exploratory): second concept (-ing) Q1-Q4 at alpha 5e-3, region A")
    L.append("")
    L.append("| model | seed | Q1 euc_dmd-dua_dmd | Q2 euc_unemb-cau_unemb | Q3 cau_unemb-dua_unemb | Q4 cau_dmd-dua_dmd |")
    L.append("|---|---|---|---|---|---|")
    for r in sorted([x for x in R if x["concept"] == "ing"], key=lambda x: (x["model"], x["seed"])):
        pl = pd.read_csv(f"{r['dir']}/paired_long.csv")
        cells = []
        for a, b in [("euc_dmd", "dua_dmd"), ("euc_unemb", "cau_unemb"), ("cau_unemb", "dua_unemb"), ("cau_dmd", "dua_dmd")]:
            q = pl[(pl.a == a) & (pl.b == b) & (pl.metric == "kl") & (np.abs(pl.level - L0) < 1e-9)]
            cells.append(fmt((q.diff_mean.iloc[0], q.diff_lo.iloc[0], q.diff_hi.iloc[0])) if len(q) else "n/a")
        L.append(f"| {r['model']} | {r['seed']} | " + " | ".join(cells) + " |")
    L.append("")
    L.append("Note: on the -ing concept the ctx/dmd probes are confounded by the auxiliary-verb frame difference "
             "(task doc WP-E); the unemb rows (Q2, Q3) are the interpretable ones.")
    L.append("")

    # ---- 5. optgap
    L.append("## 5. WP-C optimality gap (hyperplane KL minimum through each method's level-0.9 endpoint)")
    L.append("")
    L.append("| run | frac gap>=-0.01 | " + " | ".join(METHODS) + " |")
    L.append("|---|---|" + "---|" * len(METHODS))
    for d in runs_in("runs/*_v4/optgap_*"):
        if not os.path.exists(f"{d}/optgap.csv"): continue
        o = pd.read_csv(f"{d}/optgap.csv")
        g = o.groupby("method").gap.mean()
        L.append(f"| `{d}` | {(o.gap >= -0.01).mean():.3f} | " + " | ".join(f"{g.get(m, float('nan')):.2f}" if m in g.index else "n/a" for m in METHODS) + " |")
    L.append("")
    try:
        allg = pd.concat([pd.read_csv(f"{d}/optgap.csv").assign(run=d) for d in runs_in("runs/*_v4/optgap_*") if os.path.exists(f"{d}/optgap.csv")])
        p1 = allg.groupby("method")[["P1_end", "P1_opt"]].mean().round(3)
        L.append("Mean P1 at endpoint vs at the hyperplane KL-optimum (probe-invariance violation):")
        L.append("")
        L.append("| method | P1_end | P1_opt |")
        L.append("|---|---|---|")
        for m in METHODS:
            if m in p1.index: L.append(f"| {m} | {p1.loc[m, 'P1_end']:.3f} | {p1.loc[m, 'P1_opt']:.3f} |")
        L.append("")
    except Exception as e:
        L.append(f"(optgap summary failed: {e})")

    # ---- 6. cost
    L.append("## 6. WP-F cost (mean seconds and steps per context; 19 uncontended WP-A1 runs)")
    L.append("")
    L.append("| model | method | s/ctx | steps | ms/step | vs euc of same probe |")
    L.append("|---|---|---|---|---|---|")
    agg = {}
    for d in runs_in("runs/gemma1b_v4/s*") + runs_in("runs/gpt2_v4/s*") + runs_in("runs/gemma4b_v4/s*"):
        model = ("gemma-1b" if "gemma1b" in d else "gemma-4b" if "gemma4b" in d else "gpt2")
        t = pd.read_csv(f"{d}/timing.csv").groupby("method").agg(sec=("seconds", "mean"), steps=("steps_run", "mean"))
        for m, r in t.iterrows():
            agg.setdefault((model, m), []).append((r.sec, r.steps))
    for (model, m), v in sorted(agg.items()):
        if m not in METHODS: continue
        s_ = np.mean([x[0] for x in v]); st = np.mean([x[1] for x in v])
        base = agg.get((model, "euc_" + m.split("_")[-1]))
        ratio = s_ / np.mean([x[0] for x in base]) if base else float("nan")
        L.append(f"| {model} | {m} | {s_:.2f} | {st:.1f} | {1000 * s_ / max(st, 1):.0f} | {ratio:.1f}x |")
    L.append("")

    # ---- 7. evidence map
    L.append("## 7. Evidence map (machine-generated)")
    L.append("")
    L.append("| claim id | source | row reference | independent units |")
    L.append("|---|---|---|---|")
    for region, concept in [("C", "third"), ("A", "third"), ("A", "ing")]:
        rs = [r for r in R if r["region"] == region and r["concept"] == concept]
        units = sorted({(r["model"], r["seed"], r["concept"], r["region"]) for r in rs})
        for a, b, name in CONFIRM:
            L.append(f"| {name} region {region}/{concept} | " + "; ".join(f"{r['dir']}/paired_long.csv" for r in rs) +
                     f" | a={a},b={b},metric=kl,level={L0} | {len(units)} |")
    for d in runs_in("runs/*_v4/optgap_*"):
        if os.path.exists(f"{d}/optgap.csv"):
            L.append(f"| optgap @`{d}` | {d}/optgap.csv | all rows | 1 |")
    L.append("")

    # ---- figures
    try:
        import matplotlib; matplotlib.use("Agg"); import matplotlib.pyplot as plt
        # stacked decomposition bars (region A and C, alpha 5e-3, seed 0)
        fig, ax = plt.subplots(1, 2, figsize=(12, 4))
        for j, (d, ttl) in enumerate([("runs/gemma1b_v4/s0_abs5e-3", "region A (templates)"),
                                      ("runs/gemma1b_v4/c4_s0_abs5e-3", "region C (C4, park filter)")]):
            s = pd.read_csv(f"{d}/summary.csv"); s9 = s[s.level == L0].set_index("method")
            ms = [m for m in METHODS if m in s9.index]
            ax[j].bar(ms, s9.loc[ms, "klbin_mean"], label="kl_bin")
            ax[j].bar(ms, s9.loc[ms, "klpair_mean"], bottom=s9.loc[ms, "klbin_mean"], label="kl_pair")
            ax[j].bar(ms, s9.loc[ms, "klneu_mean"], bottom=s9.loc[ms, "klbin_mean"] + s9.loc[ms, "klpair_mean"], label="kl_neu")
            ax[j].set_title(ttl); ax[j].tick_params(axis="x", rotation=60); ax[j].set_ylabel("KL")
        ax[0].legend()
        fig.tight_layout(); fig.savefig("runs/fig_v4_decomp.png", dpi=150); plt.close(fig)
        # optgap boxplot
        fig, ax = plt.subplots(figsize=(10, 4))
        data = [allg[allg.method == m].gap.values for m in METHODS if (allg.method == m).any()]
        names = [m for m in METHODS if (allg.method == m).any()]
        ax.boxplot(data, tick_labels=names); ax.axhline(0, color="k", lw=0.5)
        ax.set_ylabel("gap = kl_end - kl_opt"); ax.set_title("optimality gap by method (all optgap runs)")
        ax.tick_params(axis="x", rotation=60)
        fig.tight_layout(); fig.savefig("runs/fig_v4_optgap.png", dpi=150); plt.close(fig)
        # forest: C1/C2 across regions (kl, rd, cf_dev)
        fig, axes = plt.subplots(1, 3, figsize=(15, 4))
        for j, met in enumerate(["kl", "rd", "cf_dev"]):
            k = 0
            for region in ["A", "C"]:
                for r in [x for x in R if x["region"] == region and x["concept"] == "third" and str(x["alpha"]) == "0.005"]:
                    for a, b, name in CONFIRM:
                        pl = pd.read_csv(f"{r['dir']}/paired_long.csv")
                        q = pl[(pl.a == a) & (pl.b == b) & (pl.metric == met) & (np.abs(pl.level - L0) < 1e-9)]
                        if not len(q): continue
                        row = q.iloc[0]
                        axes[j].errorbar(row.diff_mean, k, xerr=[[row.diff_mean - row.diff_lo], [row.diff_hi - row.diff_mean]], fmt="o", capsize=3)
                        axes[j].annotate(f"{name}/{region}/s{r['seed']}", (row.diff_mean, k), fontsize=5, xytext=(3, 0), textcoords="offset points")
                        k += 1
            axes[j].axvline(0, color="k", lw=0.5)
            if met == "kl": axes[j].axvspan(-EQ, EQ, alpha=0.1, color="g")
            axes[j].set_title(met); axes[j].set_yticks([])
        fig.suptitle("C1/C2 differences (a-b; >0 means b better)", fontsize=9)
        fig.tight_layout(); fig.savefig("runs/fig_v4_forest_c1c2.png", dpi=150); plt.close(fig)
        L.append("Figures: runs/fig_v4_decomp.png, runs/fig_v4_optgap.png, runs/fig_v4_forest_c1c2.png")
    except Exception as e:
        L.append(f"(figures failed: {e})")

    Path("runs/AGGREGATE_V4.md").write_text("\n".join(L) + "\n")
    print(f"wrote runs/AGGREGATE_V4.md ({len(R)} runs)")


if __name__ == "__main__":
    main()
