"""WP6: generate runs/AGGREGATE_V3.md (all tables and numbers) from the run CSV/JSON outputs.

Usage:  python aggregate.py [root1 root2 ...]     (default roots: runs/gemma1b_v3 runs/gpt2_v3 runs/gemma4b_v3)
Every number in AGGREGATE_V3.md comes from the CSVs/JSONs below those roots; nothing is hand-copied.
Figures: per-model kl/cf curves (9 methods) and a Q1-Q4 forest plot -> runs/fig_*.png
"""
import json, os, sys, glob
from pathlib import Path
import numpy as np
import pandas as pd

PRIMARY_LEVEL = 0.9
EQ_MARGIN = 0.05          # practical-equivalence margin on the KL difference (task doc section 0)
PRIMARY_PAIRS = [("euc_dmd", "dua_dmd"), ("euc_unemb", "cau_unemb"), ("cau_unemb", "dua_unemb"), ("cau_dmd", "dua_dmd")]
PRIMARY_NAMES = {("euc_dmd", "dua_dmd"): "Q1", ("euc_unemb", "cau_unemb"): "Q2",
                 ("cau_unemb", "dua_unemb"): "Q3", ("cau_dmd", "dua_dmd"): "Q4"}


def load_runs(roots):
    runs = []
    for root in roots:
        for d in sorted(glob.glob(f"{root}/*")):
            if not os.path.isdir(d) or not os.path.exists(f"{d}/summary.csv"):
                continue
            cfg = json.load(open(f"{d}/config.json")); chk = json.load(open(f"{d}/checks.json"))
            runs.append(dict(dir=d, rel=os.path.relpath(d), cfg=cfg, chk=chk,
                             data_dir=cfg["args"].get("data_dir") or "synthetic",
                             seed=cfg["args"].get("seed"), alpha=cfg["args"].get("alpha_abs"),
                             n_ctx=cfg["args"].get("n_ctx"), ridge=cfg["args"].get("ridge_rel"),
                             min_mass=cfg["args"].get("min_mass"), step_frac=cfg["args"].get("step_frac"),
                             max_steps=cfg["args"].get("max_steps")))
    return runs


def model_tag(r):
    dd = r["data_dir"]
    return ("gemma-1b" if "gemma1b" in dd else "gemma-4b" if "gemma4b" in dd else
            "gpt2" if "gpt2" in dd else "synthetic" if dd == "synthetic" else dd)


def fmt_ci(t, nd=3):
    if t is None or not np.isfinite(t[0]): return "n/a"
    return f"{t[0]:.{nd}f} [{t[1]:.{nd}f},{t[2]:.{nd}f}]"


def label(lo, hi, point, dirs):
    """Judgement labels per task doc section 5.2 D. dirs = point estimates across seeds/settings."""
    finite = [d for d in dirs if np.isfinite(d)]
    if np.isfinite(lo) and np.isfinite(hi) and -EQ_MARGIN <= lo and hi <= EQ_MARGIN:
        return "practically equivalent"
    if lo > 0:
        return "established" if (len(finite) >= 3 and all(d > 0 for d in finite)) else "consistent direction, not established"
    if np.isfinite(point) and finite and all(d > 0 for d in finite):
        return "consistent direction, not established"
    return "cannot establish"


def main(roots):
    runs = load_runs(roots)
    if not runs:
        print("no runs found under", roots); return
    L = []                                      # markdown lines
    L.append("# V3 aggregate: 3x3 probe x metric grid (auto-generated by aggregate.py)")
    L.append("")
    L.append(f"Primary level: {PRIMARY_LEVEL}; equivalence margin: +-{EQ_MARGIN} KL. All CIs are "
             "cluster bootstrap by template subject (ci_type per run in checks.json) unless noted.")
    L.append("Confirmatory comparisons: Q1-Q4 only. Everything else is exploratory (hypothesis generation).")
    L.append("Multiple comparisons: no correction applied (uncorrected). frac_ctx_b_better is a fraction of paired contexts, not a p-value.")
    L.append("")

    # ---- table 1: data & guardrails
    L.append("## 1. Data and guardrail checks")
    L.append("")
    L.append("| run | model | seed | alpha_abs | n_ctx | logits_rel_err | probe AUC | base kept | target kept | n_steered | ci_type | probe_cos (ctx-unemb / ctx-dmd / unemb-dmd) |")
    L.append("|---|---|---|---|---|---|---|---|---|---|---|---|")
    for r in runs:
        c = r["chk"]; pc = c.get("probe_cos", {})
        L.append(f"| `{r['rel']}` | {model_tag(r)} | {r['seed']} | {r['alpha']} | {r['n_ctx']} | "
                 f"{c.get('logits_rel_err'):.2e} | {c.get('probe_heldout_auc'):.3f} | {c.get('n_base_kept')}/{c.get('n_base_raw')} | "
                 f"{c.get('n_target_kept')}/{c.get('n_target_raw')} | {c.get('n_steered')} | {c.get('ci_type')} | "
                 f"{pc.get('ctx-unemb', float('nan')):.3f} / {pc.get('ctx-dmd', float('nan')):.3f} / {pc.get('unemb-dmd', float('nan')):.3f} |")
    L.append("")

    # ---- table 2: 3x3 grid at primary level (one block per run)
    L.append(f"## 2. 3x3 grid at level {PRIMARY_LEVEL}")
    L.append("")
    for r in runs:
        s = pd.read_csv(f"{r['dir']}/summary.csv")
        s = s[s.level == PRIMARY_LEVEL].set_index("method")
        L.append(f"### `{r['rel']}` ({model_tag(r)}, seed {r['seed']}, alpha_abs {r['alpha']})")
        L.append("")
        L.append("| method | reach | kl | kl99 | rd | cf | steps |")
        L.append("|---|---|---|---|---|---|---|")
        for m in ("euc_ctx", "cau_ctx", "dua_ctx", "euc_unemb", "cau_unemb", "dua_unemb", "euc_dmd", "cau_dmd", "dua_dmd"):
            if m not in s.index: continue
            row = s.loc[m]
            L.append(f"| {m} | {row.reach_rate:.2f} | {fmt_ci((row.kl_mean, row.kl_lo, row.kl_hi))} | "
                     f"{fmt_ci((row.kl99_mean, row.kl99_lo, row.kl99_hi))} | {fmt_ci((row.rd_mean, row.rd_lo, row.rd_hi))} | "
                     f"{fmt_ci((row.cf_mean, row.cf_lo, row.cf_hi))} | {row.steps_mean:.0f} |")
        L.append("")

    # ---- table 3: Q1-Q4 (all runs that have them), with labels + relative effect
    L.append(f"## 3. Pre-specified comparisons Q1-Q4 (metric = kl, level {PRIMARY_LEVEL})")
    L.append("")
    L.append("| run | Q | a | b | n_paired | diff a-b [CI] | rel (diff / mean kl of a) | frac ctx b better | verdict |")
    L.append("|---|---|---|---|---|---|---|---|---|")
    qrows = []
    for r in runs:
        p = f"{r['dir']}/paired_long.csv"
        if not os.path.exists(p): continue
        pl = pd.read_csv(p)
        pl = pl[pl.is_primary == 1]
        for _, row in pl.iterrows():
            s = pd.read_csv(f"{r['dir']}/summary.csv")
            s = s[(s.level == PRIMARY_LEVEL) & (s.method == row.a)]
            baseline = float(s.kl_mean.iloc[0]) if len(s) and np.isfinite(s.kl_mean.iloc[0]) else float("nan")
            rel = row.diff_mean / baseline if np.isfinite(baseline) and baseline != 0 else float("nan")
            qrows.append((r, row, rel))
    for r, row, rel in qrows:
        L.append(f"| `{r['rel']}` | {PRIMARY_NAMES.get((row.a, row.b), '?')} | {row.a} | {row.b} | {row.n_paired} | "
                 f"{fmt_ci((row.diff_mean, row.diff_lo, row.diff_hi))} | {rel:+.0%} | "
                 f"{row.frac_ctx_b_better} | {label(row.diff_lo, row.diff_hi, row.diff_mean, [x[1].diff_mean for x in qrows if (x[1].a, x[1].b) == (row.a, row.b)])} |")
    L.append("")
    L.append("Note: `rel` is the KL difference divided by method a's mean KL at the same level (both from the same run).")
    L.append("")

    # ---- multi-seed Q table (point estimates per seed)
    L.append("## 3b. Q1-Q4 point estimates per run/seed (direction consistency)")
    L.append("")
    for pair, name in PRIMARY_NAMES.items():
        pts = [(r["rel"], r["seed"], row.diff_mean, row.n_paired) for r, row, _ in qrows if (row.a, row.b) == pair]
        L.append(f"- **{name}** ({pair[0]} vs {pair[1]}): " + ("; ".join(
            f"`{d}` s{s}: {m:+.3f} (n={n})" for d, s, m, n in pts) if pts else "not available"))
    L.append("")

    # ---- table 4: exploratory (kl only, primary level)
    L.append(f"## 4. Exploratory comparisons (kl, level {PRIMARY_LEVEL}) - hypothesis generation only")
    L.append("")
    for r in runs:
        p = f"{r['dir']}/paired_long.csv"
        if not os.path.exists(p): continue
        pl = pd.read_csv(p)
        pl = pl[(pl.metric == "kl") & (np.abs(pl.level - PRIMARY_LEVEL) < 1e-9) & (pl.is_primary == 0)]
        if pl.empty: continue
        L.append(f"### `{r['rel']}` (exploratory)")
        L.append("")
        L.append("| a | b | n_paired | diff [CI] | frac ctx b better |")
        L.append("|---|---|---|---|---|")
        for _, row in pl.iterrows():
            L.append(f"| {row.a} | {row.b} | {row.n_paired} | {fmt_ci((row.diff_mean, row.diff_lo, row.diff_hi))} | {row.frac_ctx_b_better} |")
        L.append("")

    # ---- WP3 long-tail: kl vs kl99 for dua_* methods
    L.append("## 5. Long-tail sensitivity (WP3): kl vs kl99 for adaptive methods")
    L.append("")
    L.append("| run | method | kl | kl99 | kl99/kl |")
    L.append("|---|---|---|---|---|")
    for r in runs:
        s = pd.read_csv(f"{r['dir']}/summary.csv"); s = s[s.level == PRIMARY_LEVEL].set_index("method")
        for m in s.index:
            if not str(m).startswith("dua"): continue
            row = s.loc[m]
            if np.isfinite(row.kl_mean) and row.kl_mean > 0:
                L.append(f"| `{r['rel']}` | {m} | {row.kl_mean:.3f} | {row.kl99_mean:.3f} | {row.kl99_mean / row.kl_mean:.2f} |")
    L.append("")

    # ---- WP1 summary from repro jsons
    L.append("## 6. WP1 implementation comparison (from repro_check_data.json / repro_check_traj.json)")
    L.append("")
    if os.path.exists("repro_check_data.json") and os.path.exists("repro_check_traj.json"):
        rd = json.load(open("repro_check_data.json")); rt = json.load(open("repro_check_traj.json"))
        L.append(f"- first-step direction cosine (ours vs KihoPark/dual-steering `cg_solve`): **{rd['cos_raw']:.6f}**")
        L.append(f"- 20-step P(W=1) max relative difference (matched step size 2.0): **{rt['max_rel']:.2e}**")
        L.append(f"- 20-step entropy max abs difference: **{rt['max_H_diff']:.2e}**")
        L.append("- implementation verdict: numerically equivalent; differences are configuration (step size, stop rule, KL offset 5e-3 in their metric). See repro_check.md.")
    else:
        L.append("- repro jsons not found")
    L.append("")

    # ---- evidence map
    L.append("## 7. Evidence map (machine-generated references)")
    L.append("")
    L.append("| claim id | source file | row reference |")
    L.append("|---|---|---|")
    for r, row, _ in qrows:
        q = PRIMARY_NAMES.get((row.a, row.b), "E")
        L.append(f"| {q}: {row.a} vs {row.b} @`{r['rel']}` | {r['dir']}/paired_long.csv | level={row.level},a={row.a},b={row.b},metric=kl |")
    for r in runs:
        L.append(f"| grid @`{r['rel']}` | {r['dir']}/summary.csv | level={PRIMARY_LEVEL} |")
    L.append("")

    # ---- figures
    try:
        import matplotlib; matplotlib.use("Agg"); import matplotlib.pyplot as plt
        models = sorted({model_tag(r) for r in runs})
        for mt in models:
            rs = [r for r in runs if model_tag(r) == mt]
            fig, ax = plt.subplots(1, 2, figsize=(11, 4))
            for r in rs:
                s = pd.read_csv(f"{r['dir']}/summary.csv")
                for m in sorted(s.method.unique()):
                    ss = s[s.method == m].sort_values("level")
                    ax[0].plot(ss.level, ss.kl_mean, marker="o", label=f"{m}@a={r['alpha']}")
                    ax[1].plot(ss.level, ss.cf_mean, marker="o")
            ax[0].set_title(f"{mt}: off-target KL"); ax[1].set_title(f"{mt}: counterfactual mass")
            for a in ax: a.set_xlabel("target prob P(W=1)")
            ax[0].legend(fontsize=6, ncol=2)
            fig.tight_layout(); fig.savefig(f"runs/fig_grid_{mt.replace('-', '')}.png", dpi=150); plt.close(fig)
        fig, axes = plt.subplots(1, 4, figsize=(16, 3.5))
        for j, met in enumerate(("kl", "kl99", "rd", "cf")):
            k = 0
            for r in runs:
                p = f"{r['dir']}/paired_long.csv"
                if not os.path.exists(p): continue
                pl = pd.read_csv(p)
                mask = np.array([(a, b) in PRIMARY_PAIRS for a, b in zip(pl.a, pl.b)])
                sel = pl[(pl.metric == met) & (np.abs(pl.level - PRIMARY_LEVEL) < 1e-9) & mask]
                for _, row in sel.iterrows():
                    axes[j].errorbar(row.diff_mean, k, xerr=[[row.diff_mean - row.diff_lo], [row.diff_hi - row.diff_mean]],
                                     fmt="o", capsize=3)
                    axes[j].annotate(f"{PRIMARY_NAMES.get((row.a, row.b))}@{r['alpha']}", (row.diff_mean, k), fontsize=6,
                                     xytext=(3, 0), textcoords="offset points")
                    k += 1
            axes[j].axvline(0, color="k", lw=0.5)
            if met == "kl": axes[j].axvspan(-EQ_MARGIN, EQ_MARGIN, alpha=0.1, color="g")
            axes[j].set_title(met); axes[j].set_yticks([])
        fig.suptitle("Q1-Q4 differences (a-b; >0 means b better)", fontsize=9)
        fig.tight_layout(); fig.savefig("runs/fig_forest_q1q4.png", dpi=150); plt.close(fig)
        L.append(f"Figures: runs/fig_grid_*.png ({', '.join(models)}), runs/fig_forest_q1q4.png")
        L.append("")
    except Exception as e:
        L.append(f"(figure generation failed: {e})")

    Path("runs/AGGREGATE_V3.md").write_text("\n".join(L) + "\n")
    print(f"wrote runs/AGGREGATE_V3.md ({len(runs)} runs)")


if __name__ == "__main__":
    main(sys.argv[1:] or ["runs/gemma1b_v3", "runs/gpt2_v3", "runs/gemma4b_v3"])
